//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Closure_Day
    {
        public int csdID { get; set; }

        [Display(Name = "Start Day")]
        public System.DateTime startDay { get; set; }

        [Display(Name = "End Day")]
        public System.DateTime endDay { get; set; }

        [Display(Name = "Final Day")]
        public System.DateTime finalDay { get; set; }
    }
}
