//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contribution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contribution()
        {
            this.Images = new HashSet<Image>();
            this.Comments = new HashSet<Comment>();
        }

        [Display(Name = "ContributionID")]
        public int consID { get; set; }

        [Display(Name = "Name")]
        public string cons_Name { get; set; }

        [Display(Name = "Comment")]
        public string cons_comment { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]

        [Display(Name = "Date Submit")]
        public Nullable<System.DateTime> cons_submit { get; set; }

        [Display(Name = "Status")]
        public string cons_status { get; set; }

        [Display(Name = "StudentID")]
        public int stdID { get; set; }

        [Display(Name = "FileID")]
        public int fileID { get; set; }
    
        public virtual File File { get; set; }
        public virtual User_Student_Detail User_Student_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
