//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contribution
    {
        [Required]
        [Display(Name = "Constribution ID")]
        public int consID { get; set; }

        [Required]
        [Display(Name = "Tittle")]
        public string cons_Name { get; set; }

        [Display(Name = "Comment")]
        public string cons_comment { get; set; }

        [Required]
        [Display(Name = "Submit Date")]
        public Nullable<System.DateTime> cons_submit { get; set; }

        [Required]
        [Display(Name = "Status")]
        public string cons_status { get; set; }

        [Required]
        [Display(Name = "Student ID")]
        public int stdID { get; set; }

        [Required]
        [Display(Name = "File ID")]
        public int fileID { get; set; }
    
        public virtual File File { get; set; }
        public virtual User_Student_Detail User_Student_Detail { get; set; }
    }
}
