//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        [Display(Name = "ID")]
        public int imgID { get; set; }

        [Display(Name = "Image Tittle")]
        public string img_Title { get; set; }
        [Display(Name = "ContributionID")]
        public int consID { get; set; }
    
        public virtual Contribution Contribution { get; set; }
    }
}
