//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing_Coordinator
    {
        public int mkcID { get; set; }
        public string mkc_username { get; set; }
        public string mkc_password { get; set; }
        public string mkc_fullname { get; set; }
        public string mkc_mail { get; set; }
        public string mkc_gender { get; set; }
        public Nullable<System.DateTime> mkc_doB { get; set; }
        public string mkc_phone { get; set; }
        public int facID { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
