//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebEntepriseEntities2 : DbContext
    {
        public WebEntepriseEntities2()
            : base("name=WebEntepriseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Closure_Day> Closure_Days { get; set; }
        public virtual DbSet<Contribution> Contributions { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Marketing_Coordinator> Marketing_Coordinators { get; set; }
        public virtual DbSet<Marketing_Manager> Marketing_Managers { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
