//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Guest_Detail
    {

        [Display(Name = "UserID")]
        public string userId { get; set; }

        [Display(Name = "GuestID")]
        public int gstID { get; set; }

        [Display(Name = "Fullname")]
        public string gst_fullname { get; set; }

        [Display(Name = "Mail")]
        public string gst_mail { get; set; }

        [Display(Name = "Gender")]
        public string gst_gender { get; set; }

        [Display(Name = "Date of birth")]
        public Nullable<System.DateTime> gst_doB { get; set; }

        [Display(Name = "Phone")]
        public string gst_phone { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
