//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Marketing_Manager_Detail
    {
        [Required]
        [Display(Name = "User ID")]
        public string userId { get; set; }

        [Required]
        [Display(Name = "ID")]
        public int mkmID { get; set; }

        [Required]
        [Display(Name = "Fullname")]
        public string mkm_fullname { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string mkm_mail { get; set; }

        [Required]
        [Display(Name = "Gender")]
        public string mkm_gender { get; set; }

        [Required]
        [Display(Name = "Date of Birth")]
        public Nullable<System.DateTime> mkm_doB { get; set; }

        [Required]
        [Display(Name = "Phone numbers")]
        public string mkm_phone { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
