//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Guest_Detail
    {
        public string userId { get; set; }
        public int gstID { get; set; }
        public string gst_fullname { get; set; }
        public string gst_mail { get; set; }
        public string gst_gender { get; set; }
        public Nullable<System.DateTime> gst_doB { get; set; }
        public string gst_phone { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
