//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int admID { get; set; }
        public string admin_username { get; set; }
        public string admin_password { get; set; }
        public string admin_fullname { get; set; }
        public string admin_mail { get; set; }
        public string admin_gender { get; set; }
        public Nullable<System.DateTime> admin_doB { get; set; }
        public string admin_phone { get; set; }
    }
}
